### ISSUE TITLE
Is IDE support possible at this stage?

### ISSUE THREAD

**Issue by ak-seyam** [bowbahdoe/magic-bean#1]

**Comment by bowbahdoe** [comment]
Yep. Most IDEs should already handle this via their generic support for generated sources.

Here is a recording of the workflow in IntelliJ

![ide-support](https://user-images.githubusercontent.com/5004262/150656579-27cf2470-f900-4c82-9248-740381f222f4.gif)

**Comment by ak-seyam** [comment]
Unfortunately, my case is different.  

https://user-images.githubusercontent.com/34966791/150657138-0b77d9b5-6f8d-41bf-bb9a-c0c1d1379bbd.mp4


These are my settings for SDK version and compiler
![Screenshot from 2022-01-23 00-20-13](https://user-images.githubusercontent.com/34966791/150657308-aa535274-b63f-4275-a3a2-978ec9ae24af.png)
![Screenshot from 2022-01-23 00-20-36](https://user-images.githubusercontent.com/34966791/150657309-d2f71531-b6b2-48d9-a9e9-b375604f07b2.png)

Any troubleshooting steps? 

Thanks.

**Comment by bowbahdoe** [comment]
I'll dig into how to make it happen automatically - I'm sure there is a way - but what I'm doing is just right clicking the generated source folder under target and clicking "Mark as generated sources root"

**Comment by bowbahdoe** [comment]
I think for maven adding this snippet will let intelliJ automatically detect it

https://stackoverflow.com/questions/5170620/unable-to-use-intellij-with-a-generated-sources-folder

```xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>build-helper-maven-plugin</artifactId>
    <version>1.4</version>
    <executions>
        <execution>
            <id>test</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>add-source</goal>
            </goals>
            <configuration>
                <sources>
                    <source>${basedir}/target/generated-sources</source>
                </sources>
            </configuration>
        </execution>
    </executions>
</plugin>
```

A little strange, but take that up with Maven/Jetbrains

**Comment by bowbahdoe** [comment]
![mark](https://user-images.githubusercontent.com/5004262/150657951-5e5cb5d5-3dd9-4c5e-9fb9-38839c98f44a.gif)

**Comment by ak-seyam** [comment]
> I think for maven adding this snippet will let intelliJ automatically detect it
> 
> https://stackoverflow.com/questions/5170620/unable-to-use-intellij-with-a-generated-sources-folder
> 
> ```
> <plugin>
>     <groupId>org.codehaus.mojo</groupId>
>     <artifactId>build-helper-maven-plugin</artifactId>
>     <version>1.4</version>
>     <executions>
>         <execution>
>             <id>test</id>
>             <phase>generate-sources</phase>
>             <goals>
>                 <goal>add-source</goal>
>             </goals>
>             <configuration>
>                 <sources>
>                     <source>${basedir}/target/generated-sources</source>
>                 </sources>
>             </configuration>
>         </execution>
>     </executions>
> </plugin>
> ```
> 
> A little strange, but take that up with Maven/Jetbrains

This worked for me, thanks
