### ISSUE TITLE
Automatic Intellij Refreshing

### ISSUE THREAD

**Issue by funkrusher** [bowbahdoe/magic-bean#23]
Hello,

really nice project!

When working in Intellij IDEA, when editing/writing a new Bean like this...
```
import dev.mccue.magicbean.MagicBean;

import java.util.List;

@MagicBean
public final class Example extends ExampleBeanOps {
    int x;
    String name;
    List<String> strs;
}
```
... the next step for me (using gradle) is to go to the console and write:
```
./gradlew compileJava
```

After i execute this statement the magic-beans creates the `ExampleBeanOps` as expected.

It would be great if Intellij would be able to automatically do this in the background somehow.

An accetable solution would be: 
- the need to click an already existing button/feature like the "Gradle Refresh Icon".
- new developers should check out the project and immediately can start working with it in Intellij without the need to create own configurations for starting this refesh-task
- an intellij plugin would be acceptable as it only involves the user to install this from the intellij marketplace.

A non-plugin solution is preferred.

**Comment by funkrusher** [comment]
ah well, never mind.

i just need to click "build" or "rebuild project" in intellij, and everything works after clicking this button.
That is already good enough in my opinion. 

Intellij automatically configures the annotation processor for the gradle build via "gradle refresh" or when first importing the project into intellij. 

For me its fine.

**Comment by bowbahdoe** [comment]
Yeah - obviously an IntelliJ plugin would make that process smoother, but sans a plugin thats the experience you get.
