### ISSUE TITLE
Include a gradle snippet in the readme

### ISSUE THREAD

**Issue by bowbahdoe** [bowbahdoe/magic-bean#5]
This should work with gradle no problem - I just don't know the exact incantation to put in the readme.

Maybe a regular gradle user could help here?

**Comment by apollofps** [comment]
hi i would like to work on this issue . can you assign me

**Comment by bowbahdoe** [comment]
@apollofps Any updates?

**Comment by bowbahdoe** [comment]
Closed by #18
